import type { ProviderConfig, Settings } from "@/shared/types";

export const DEFAULT_PROVIDERS: ProviderConfig[] = [
  { id: "demo", label: "Demo Mode", enabled: true, model: "demo-solver", supportsCatalog: false },
  {
    id: "openai",
    label: "OpenAI",
    enabled: false,
    model: "gpt-4o-mini",
    baseUrl: "https://api.openai.com/v1",
    temperature: 0.2,
    maxTokens: 2048,
    supportsCatalog: true,
  },
  {
    id: "gemini",
    label: "Google Gemini",
    enabled: false,
    model: "gemini-2.0-flash",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    temperature: 0.2,
    maxTokens: 2048,
    supportsCatalog: true,
  },
  {
    id: "anthropic",
    label: "Anthropic Claude",
    enabled: false,
    model: "claude-3-5-haiku-latest",
    baseUrl: "https://api.anthropic.com",
    temperature: 0.2,
    maxTokens: 2048,
    supportsCatalog: false,
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    enabled: false,
    model: "openrouter/auto",
    baseUrl: "https://openrouter.ai/api/v1",
    temperature: 0.2,
    maxTokens: 2048,
    supportsCatalog: true,
  },
  {
    id: "groq",
    label: "Groq",
    enabled: false,
    model: "llama-3.3-70b-versatile",
    baseUrl: "https://api.groq.com/openai/v1",
    temperature: 0.2,
    maxTokens: 2048,
    supportsCatalog: true,
  },
  {
    id: "mistral",
    label: "Mistral AI",
    enabled: false,
    model: "mistral-small-latest",
    baseUrl: "https://api.mistral.ai/v1",
    temperature: 0.2,
    maxTokens: 2048,
    supportsCatalog: true,
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    enabled: false,
    model: "deepseek-chat",
    baseUrl: "https://api.deepseek.com/v1",
    temperature: 0.2,
    maxTokens: 2048,
    supportsCatalog: true,
  },
  {
    id: "together",
    label: "Together AI",
    enabled: false,
    model: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
    baseUrl: "https://api.together.xyz/v1",
    temperature: 0.2,
    maxTokens: 2048,
    supportsCatalog: true,
  },
  {
    id: "fireworks",
    label: "Fireworks AI",
    enabled: false,
    model: "accounts/fireworks/models/llama-v3p1-8b-instruct",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    temperature: 0.2,
    maxTokens: 2048,
    supportsCatalog: true,
  },
  {
    id: "cerebras",
    label: "Cerebras",
    enabled: false,
    model: "llama3.1-8b",
    baseUrl: "https://api.cerebras.ai/v1",
    temperature: 0.2,
    maxTokens: 2048,
    supportsCatalog: true,
  },
  {
    id: "cohere",
    label: "Cohere",
    enabled: false,
    model: "command-r-plus",
    baseUrl: "https://api.cohere.com/v2",
    temperature: 0.2,
    maxTokens: 2048,
    supportsCatalog: false,
  },
  {
    id: "huggingface",
    label: "Hugging Face",
    enabled: false,
    model: "meta-llama/Meta-Llama-3-8B-Instruct",
    baseUrl: "https://router.huggingface.co/v1",
    temperature: 0.2,
    maxTokens: 2048,
    supportsCatalog: false,
  },
  {
    id: "ollama",
    label: "Ollama (local)",
    enabled: false,
    model: "llama3.2",
    baseUrl: "http://127.0.0.1:11434",
    temperature: 0.2,
    maxTokens: 2048,
    supportsCatalog: true,
  },
  {
    id: "lmstudio",
    label: "LM Studio (local)",
    enabled: false,
    model: "local-model",
    baseUrl: "http://127.0.0.1:1234/v1",
    temperature: 0.2,
    maxTokens: 2048,
    supportsCatalog: true,
  },
  {
    id: "custom",
    label: "Custom OpenAI-compatible",
    enabled: false,
    model: "custom-model",
    baseUrl: "http://127.0.0.1:8080/v1",
    temperature: 0.2,
    maxTokens: 2048,
    supportsCatalog: true,
  },
];

export const DEFAULT_SETTINGS: Settings = {
  theme: "dark",
  accent: "cyan",
  fontSize: "md",
  density: "comfortable",
  animations: true,
  floatingToolbar: false,
  floatingToolbarExcludedHosts: [],
  answerMode: "learn",
  explanationDepth: "balanced",
  expertiseLevel: "intermediate",
  preferredLanguage: "en",
  answerFirst: true,
  showFormulas: true,
  showAlternatives: true,
  explainIncorrectOptions: true,
  confirmBatchSolve: true,
  ocrLanguage: "eng",
  autoDetectBoundaries: true,
  captureDelayMs: 0,
  batchLimit: 10,
  defaultProvider: "demo",
  providers: DEFAULT_PROVIDERS,
  systemInstructions:
    "You are SnapSolve AI by Tarik Islam (https://tarikislam.in), a careful study companion. Help the user learn. Do not encourage cheating on active graded exams. Prefer explanations and conceptual guidance for assessments. Never invent citations.",
  requestTimeoutMs: 60000,
  retryCount: 1,
  historyRetentionDays: 30,
  historyEnabled: true,
  discloseExternalTransfer: true,
  onboardingComplete: false,
  demoMode: true,
  routingMode: "automatic",
  allowPaidModels: true,
  freeOnlyMode: false,
  verifyAnswers: false,
  catalogCacheMinutes: 60,
  requestsToday: 0,
  requestsDayKey: "",
  exportIncludeBranding: true,
  requireConsentBeforeExternal: true,
  consentedExternalTransfer: false,
  taskModels: {},
};

export const BRAND = {
  product: "SnapSolve AI",
  creator: "Tarik Islam",
  attribution: "Made by TarikIslam.in",
  website: "https://tarikislam.in",
} as const;
