export const portfolioData = [
  // Education
  { title: "Great India Public School", url: "https://greatindiapublicschool.org/", category: "Education", isLive: true },
  { title: "Sorobana Abacus Academy", url: "https://www.sorobanabacusacademy.com/", category: "Education", isLive: true },
  { title: "Babusirs Group Tuitions", url: "https://babusirsgrouptuitions.com", category: "Education", isLive: true },
  { title: "Smart Bankers Institute", url: "https://smartbankersinstitute.com/", category: "Education", isLive: true },
  
  // Beauty & Fashion
  { title: "Yasana Beauty Rituals", url: "https://yasanabeautyrituals.in/", category: "Beauty & Fashion", isLive: true },
  { title: "Aura Mantra", url: "https://auramantra.co/", category: "Beauty & Fashion", isLive: true },
  { title: "Zavique", url: "https://zavique.in/", category: "Beauty & Fashion", isLive: true },
  { title: "Sonvica Sarees", url: "https://sonvicasarees.com/", category: "Beauty & Fashion", isLive: true },
  { title: "Bloom Blush Beauty", url: "https://bloomblushbeauty.com/", category: "Beauty & Fashion", isLive: true },
  { title: "Vientro", url: "https://vientro.co/", category: "Beauty & Fashion", isLive: true },
  { title: "Glamifyra", url: "https://glamifyra.co/", category: "Beauty & Fashion", isLive: true },
  { title: "Vistaaar", url: "https://vistaaar.in/", category: "Beauty & Fashion", isLive: true },
  { title: "Play N Wear", url: "http://playnwear.in/", category: "Beauty & Fashion", isLive: true },
  { title: "YOYO Fashion", url: "https://www.yoyo.fashion/", category: "Beauty & Fashion", isLive: true },
  { title: "Nakshatra Ethnic Store", url: "https://nakshatraethnicstore.com", category: "Beauty & Fashion", isLive: true },
  { title: "Kessawear", url: "https://www.kessawear.com/", category: "Beauty & Fashion", isLive: true },
  { title: "Peony Kids Couture", url: "https://www.peonykidscouture.com/", category: "Beauty & Fashion", isLive: true },
  { title: "Alvizaron", url: "https://www.alvizaron.com/", category: "Beauty & Fashion", isLive: true },
  { title: "Cottons Jaipur", url: "https://cottonsjaipur.com/", category: "Beauty & Fashion", isLive: true },
  { title: "Beyoung", url: "https://www.beyoung.in/", category: "Beauty & Fashion", isLive: true },
  { title: "Cilory", url: "https://www.cilory.com/", category: "Beauty & Fashion", isLive: true },
  { title: "Krishna Sarees", url: "https://www.krishnasarees.co.in/", category: "Beauty & Fashion", isLive: true },
  { title: "Shadan Silk", url: "https://www.shadansilk.com/", category: "Beauty & Fashion", isLive: true },
  { title: "Auryah Vastram", url: "https://www.auryahvastram.com/", category: "Beauty & Fashion", isLive: true },
  { title: "Yous World", url: "https://yousworld.in", category: "Beauty & Fashion", isLive: true },
  { title: "SS Fashions", url: "https://ssfashions.co.in", category: "Beauty & Fashion", isLive: true },
  { title: "Rupamkart", url: "https://rupamkart.com", category: "Beauty & Fashion", isLive: true },
  { title: "Trendy Pinks", url: "https://trendypinks.in", category: "Beauty & Fashion", isLive: true },
  { title: "Animade", url: "https://animade.in", category: "Beauty & Fashion", isLive: true },
  { title: "Stygg89", url: "https://stygg89.com", category: "Beauty & Fashion", isLive: true },
  { title: "Devansh Vasthralaya", url: "https://devanshvasthralaya.com", category: "Beauty & Fashion", isLive: true },
  { title: "Dra Fashion", url: "https://drafashion.com", category: "Beauty & Fashion", isLive: true },
  { title: "The Goated Aisle", url: "https://thegoatedaisle.com", category: "Beauty & Fashion", isLive: true },
  { title: "My Shaby Arisha", url: "https://myshabyarisha.com", category: "Beauty & Fashion", isLive: true },
  { title: "Sanvis Fashion", url: "https://sanvisfashion.com", category: "Beauty & Fashion", isLive: true },
  { title: "Dhyuti", url: "https://dhyuti.in", category: "Beauty & Fashion", isLive: true },
  { title: "Shana Stores", url: "https://shanastores.in", category: "Beauty & Fashion", isLive: true },
  { title: "Thread Arc", url: "https://threadarc.in", category: "Beauty & Fashion", isLive: true },
  { title: "Yaazh Clothing", url: "https://yaazhclothing.in", category: "Beauty & Fashion", isLive: true },
  { title: "Vasthreeyam", url: "https://vasthreeyam.com", category: "Beauty & Fashion", isLive: true },
  { title: "Weave and Weavers", url: "https://weaveandweavers.com", category: "Beauty & Fashion", isLive: true },
  { title: "Sutranzo", url: "https://sutranzo.com", category: "Beauty & Fashion", isLive: true },
  { title: "Hangbang", url: "https://hangbang.in", category: "Beauty & Fashion", isLive: true },
  { title: "Kids E Zone", url: "https://kidsezone.com", category: "Beauty & Fashion", isLive: true },
  { title: "One 7 Store", url: "https://one7store.in", category: "Beauty & Fashion", isLive: true },
  { title: "Shoe Gallery", url: "https://shoegallery.co.in", category: "Beauty & Fashion", isLive: true },
  { title: "Walai", url: "https://walai.in", category: "Beauty & Fashion", isLive: true },
  { title: "Seoul Beauty Zone", url: "https://seoulbeautyzone.com", category: "Beauty & Fashion", isLive: true },
  { title: "Lakarv", url: "https://lakarv.com", category: "Beauty & Fashion", isLive: true },
  { title: "Silk Flair", url: "https://silkflair.in", category: "Beauty & Fashion", isLive: true },
  { title: "Beautenza", url: "https://beautenza.in", category: "Beauty & Fashion", isLive: true },
  
  // Healthcare
  { title: "Shree Ayurved", url: "https://www.shreeayurved.com/", category: "Healthcare", isLive: true },
  { title: "Shree Ayurveda", url: "https://shreeayurveda.co.in", category: "Healthcare", isLive: true },
  { title: "Neuro Ayurgenix", url: "https://neuroayurgenix.com", category: "Healthcare", isLive: true },
  { title: "BioBonz", url: "https://biobonz.com/", category: "Healthcare", isLive: true },
  { title: "Prazie Ayurveda", url: "https://prazieayurveda.com", category: "Healthcare", isLive: true },
  { title: "Spectrum Homeopathy", url: "https://spectrumhomeopathy.com/", category: "Healthcare", isLive: true },
  { title: "Om Life Care", url: "https://www.omlifecare.org/", category: "Healthcare", isLive: true },
  { title: "Surgery By Dr Praveen", url: "https://surgerybydrpraveen.in/", category: "Healthcare", isLive: true },
  { title: "Genesis Health Campus", url: "https://genesishealthcampus.com/", category: "Healthcare", isLive: true },
  { title: "Ainaya Global", url: "https://ainayaglobal.com", category: "Healthcare", isLive: true },
  { title: "MS Clinic", url: "https://msclinic.online", category: "Healthcare", isLive: true },
  { title: "Siya Herbs", url: "https://siyaherbs.com", category: "Healthcare", isLive: true },
  { title: "Padmam Naturals", url: "https://padmamnaturals.com", category: "Healthcare", isLive: true },
  { title: "Sankalpa Ayurveda", url: "https://sankalpaayurveda.in", category: "Healthcare", isLive: true },
  { title: "Herbozz Natural", url: "https://herbozznatural.com", category: "Healthcare", isLive: true },
  { title: "Deep Calm", url: "https://deepcalm.in", category: "Healthcare", isLive: true },

  // Corporate
  { title: "Nilkanth Paints", url: "https://nilkanthpaints.com/", category: "Corporate", isLive: true },
  { title: "AFK Advisors", url: "https://afkadvisors.in/", category: "Corporate", isLive: true },
  { title: "Agrowusha Global", url: "https://agrowushaglobal.com/", category: "Corporate", isLive: true },
  { title: "EVTeker Europe", url: "https://evtekereurope.com", category: "Corporate", isLive: true },
  { title: "Dark Alert Security Pvt Ltd", url: "https://darkalertsecuritypvtltd.com", category: "Corporate", isLive: true },
  { title: "Career Script", url: "https://careerscript.co.in", category: "Corporate", isLive: true },
  { title: "DS Groups", url: "https://dsgroups.in/", category: "Corporate", isLive: true },
  { title: "Prominent Technolabs", url: "https://www.prominenttechnolabs.com/", category: "Corporate", isLive: true },
  { title: "Wallfast Precast", url: "https://www.wallfastprecast.in/", category: "Corporate", isLive: true },
  { title: "SLN Tiles Showroom", url: "https://www.slntilesshowroom.com", category: "Corporate", isLive: true },
  { title: "Shaikh Furniture", url: "https://shaikhfurniture.in", category: "Corporate", isLive: true },
  { title: "Elite Metro Car Rental", url: "https://elitemetrocarrental.in", category: "Corporate", isLive: true },
  { title: "Shushrusha NGO", url: "https://shushrusha.ngo", category: "Corporate", isLive: true },
  { title: "Least Action Company", url: "https://www.leastactioncompany.com/", category: "Corporate", isLive: true },
  { title: "City Wash", url: "https://citywash.co.in/", category: "Corporate", isLive: true },
  { title: "Secure View", url: "https://www.secureview.in/", category: "Corporate", isLive: true },
  { title: "Vagmine Smartech", url: "https://www.vagminesmartechindustries.com/", category: "Corporate", isLive: true },
  { title: "Allied Vents", url: "https://www.alliedvents.com/", category: "Corporate", isLive: true },
  { title: "ZMS Logistics", url: "https://www.zmslogisticspvtltd.com/", category: "Corporate", isLive: true },
  { title: "Nissy Charitable Trust", url: "https://www.nissycharitabletrust.org/", category: "Corporate", isLive: true },
  { title: "Samaria Pathways", url: "https://www.samariapathways.com/", category: "Corporate", isLive: true },
  { title: "Rohit Enterprises", url: "https://rohitenterprises.org/", category: "Corporate", isLive: true },
  { title: "Sat-Con", url: "https://sat-con.in/", category: "Corporate", isLive: true },
  { title: "Powcal", url: "https://powcal.in/", category: "Corporate", isLive: true },
  { title: "Ambience Decor", url: "https://ambiencedecor.in/", category: "Corporate", isLive: true },
  { title: "The White Tusk", url: "https://www.thewhitetusk.com/", category: "Corporate", isLive: true },
  { title: "Aim Inter Consuting", url: "https://aiminterconsuting.com", category: "Corporate", isLive: true },
  { title: "Blue Electricals", url: "https://bluelectricals.com", category: "Corporate", isLive: true },
  { title: "Build For 100", url: "https://buildfor100.in", category: "Corporate", isLive: true },
  { title: "Sasveen Financial Services", url: "https://sasveenfinancialservices.com", category: "Corporate", isLive: true },
  { title: "CRDC", url: "https://crdc.org.in", category: "Corporate", isLive: true },
  { title: "Keen And Clean Services", url: "https://keenandcleanservices.com", category: "Corporate", isLive: true },
  { title: "VCare Services", url: "https://vcareservices.co.in", category: "Corporate", isLive: true },
  { title: "ASFL Warehouse And Logistics", url: "https://asflwarehouseandlogistics.com", category: "Corporate", isLive: true },
  
  // Real Estate
  { title: "Dream Property", url: "https://www.dreamproperty.qa/", category: "Real Estate", isLive: true },
  { title: "Best House Qatar", url: "https://www.besthouseqatar.com/", category: "Real Estate", isLive: true },
  { title: "Mirage Property", url: "https://mirageproperty.com/", category: "Real Estate", isLive: true },
  { title: "Your Realtors", url: "https://yourrealtors.com.au/", category: "Real Estate", isLive: true },
  { title: "Salahkaar Realtors", url: "https://salahkaarrealtors.com/", category: "Real Estate", isLive: true },
  { title: "Sai Swastik Constructions", url: "https://saiswastikconstructions.com", category: "Real Estate", isLive: true },
  { title: "Shri Sairam Homes", url: "https://shrisairamhomes.com", category: "Real Estate", isLive: true },

  // Ecommerce & Miscellaneous
  { title: "The Paan Luxe", url: "https://thepaanluxe.com", category: "Ecommerce", isLive: true },
  { title: "Pradiyas", url: "https://pradiyas.com", category: "Ecommerce", isLive: true },
  { title: "Kadence", url: "https://kadence.in/", category: "Ecommerce", isLive: true },
  { title: "Official Watches", url: "https://www.officialwatches.com/", category: "Ecommerce", isLive: true },
  { title: "Fizzy Goblet", url: "https://fizzygoblet.com/", category: "Ecommerce", isLive: true },
  { title: "The Olio Stories", url: "https://theoliostories.com/", category: "Ecommerce", isLive: true },
  { title: "18 Herbs", url: "https://18herbs.com/", category: "Ecommerce", isLive: true },
  { title: "Aashi Luxe Crafts", url: "https://www.aashiluxecrafts.com/", category: "Ecommerce", isLive: true },
  { title: "Starlight Impex", url: "https://www.starlightimpex.com/", category: "Ecommerce", isLive: true },
  { title: "Cidlex Trade India", url: "https://www.cidlextradeindia.com/", category: "Ecommerce", isLive: true },
  { title: "Golden Global Goals", url: "https://www.goldenglobalgoals.com/", category: "Ecommerce", isLive: true },
  { title: "Shri Meenakshi Diamonds", url: "https://shrimeenakshidiamonds.com/", category: "Ecommerce", isLive: true },
  { title: "Techkaart", url: "https://techkaart.com", category: "Ecommerce", isLive: true },
  { title: "Electikart", url: "https://electikart.com", category: "Ecommerce", isLive: true },
  { title: "Luxline", url: "https://luxline.in", category: "Ecommerce", isLive: true },
  { title: "Mobilook", url: "https://mobilook.in", category: "Ecommerce", isLive: true },
  { title: "Kidultz", url: "https://kidultz.in", category: "Ecommerce", isLive: true },
  { title: "Hexpods", url: "https://hexpods.in", category: "Ecommerce", isLive: true },
  { title: "AR Enterprises", url: "https://arenterprises.store", category: "Ecommerce", isLive: true },
  { title: "Vipsi", url: "https://vipsi.in", category: "Ecommerce", isLive: true },
  { title: "Deoria Mart", url: "https://deoriamart.com", category: "Ecommerce", isLive: true },
  { title: "Merzmart", url: "https://merzmart.in", category: "Ecommerce", isLive: true },
  { title: "The Wooden Petal", url: "https://thewoodenpetal.in", category: "Ecommerce", isLive: true },
  { title: "Comic Store", url: "https://comicstore.in", category: "Ecommerce", isLive: true },
  { title: "Home Storiey", url: "https://homestoriey.co.in", category: "Ecommerce", isLive: true },
  { title: "Royal Furn Interiors", url: "https://royalfurninteriors.com", category: "Ecommerce", isLive: true },
  { title: "Diwan Fitness", url: "https://diwanfitness.com", category: "Ecommerce", isLive: true },
  
  // Food & Grocery
  { title: "Shitija Snacks", url: "https://shitijasnacks.com/", category: "Food & Grocery", isLive: true },
  { title: "The Thirsty Crow", url: "https://www.thethirstycrow.co/", category: "Food & Grocery", isLive: true },
  { title: "Milkim", url: "https://milkim.com/", category: "Food & Grocery", isLive: true },
  { title: "Fitnacks Foods", url: "https://fitnacksfoods.com/", category: "Food & Grocery", isLive: true },
  { title: "Pollachi Vivasaayi", url: "https://pollachivivasaayi.in", category: "Food & Grocery", isLive: true },
  { title: "Rich Relish", url: "https://richrelish.in", category: "Food & Grocery", isLive: true },
  { title: "Spice Paradise", url: "https://spiceparadise.co.in", category: "Food & Grocery", isLive: true },
  { title: "Way Roots", url: "https://wayroots.in", category: "Food & Grocery", isLive: true },
  { title: "Kampu", url: "https://kampu.in", category: "Food & Grocery", isLive: true },
  { title: "Khaana Makhana", url: "https://khaanamakhana.com", category: "Food & Grocery", isLive: true },
  { title: "Vinika Food Thoughts", url: "https://vinikafoodthoughts.in", category: "Food & Grocery", isLive: true },
  { title: "Earthly Affairs", url: "https://earthlyaffairs.in", category: "Food & Grocery", isLive: true },
  { title: "Go Satvik", url: "https://gosatvik.co.in", category: "Food & Grocery", isLive: true },
  { title: "Happy Foodss", url: "https://happyfoodss.com", category: "Food & Grocery", isLive: true },
  { title: "Muskan Agro Foods", url: "https://muskanagrofoods.com", category: "Food & Grocery", isLive: true },
  { title: "Akchu Home Foods", url: "https://akchuhomefoods.in", category: "Food & Grocery", isLive: true },
  { title: "Gumghatti Products", url: "https://gumghattiproducts.com", category: "Food & Grocery", isLive: true },
  { title: "Maa Healthy Treat", url: "https://maahealthytreat.in", category: "Food & Grocery", isLive: true },
  { title: "Eat Right Eat Well", url: "https://eatrighteatwell.com", category: "Food & Grocery", isLive: true },
  
  // Photography
  { title: "8K Entertainment Media", url: "https://8kentertainmentmedia.com/", category: "Photography", isLive: true },
  { title: "Mumbai Films", url: "https://mumbaifilms.in/", category: "Photography", isLive: true },
  { title: "Spectadors Studios", url: "https://spectadorsstudios.com/", category: "Photography", isLive: true },
  { title: "PK Photography", url: "https://pkphotography.in/", category: "Photography", isLive: true },
  { title: "The Photo Lab", url: "https://www.thephotolab.co.in/", category: "Photography", isLive: true },
  { title: "Photo Portray", url: "https://www.photoportray.com/", category: "Photography", isLive: true },
  { title: "Classy Clicks Photography", url: "https://classyclicksphotography.com/", category: "Photography", isLive: true },

  // Marketing
  { title: "Exim Pathshala", url: "https://eximpathshala.com/", category: "Marketing", isLive: true },
  { title: "Propleadz", url: "https://propleadz.in/", category: "Marketing", isLive: true },
  { title: "Digiland 4u", url: "https://digiland4u.com", category: "Marketing", isLive: true },
  
  // Media
  { title: "Pooch Wooch", url: "https://poochwooch.in/", category: "Media", isLive: true },
  { title: "Antyodaya News", url: "https://antyodayanews.com/", category: "Media", isLive: true },
  
  // Travel & Hospitality
  { title: "Hotel Drip Inn", url: "https://hoteldripinn.com", category: "Hospitality", isLive: true },
  { title: "Pilibhit Safari Homestay", url: "https://www.pilibhitsafarihomestay.com/", category: "Hospitality", isLive: true },
  { title: "Melody Moon Resort", url: "https://melodymoonresort.com/", category: "Hospitality", isLive: true },
  { title: "Jai Bhavani Travels", url: "https://jaibhavani.in", category: "Travel", isLive: true },
  { title: "Tourissima Tours", url: "https://tourissimatours.in/", category: "Travel", isLive: true },
  { title: "Stagway Travels", url: "https://stagwaytravels.com/", category: "Travel", isLive: true },
  { title: "Coral Wings Andaman", url: "https://coralwingsandaman.online", category: "Travel", isLive: true },
  { title: "Oye Taxis", url: "https://oyetaxis.in/", category: "Travel", isLive: true },
  { title: "Divy Travel Solutions", url: "https://divytravelsolutions.com", category: "Travel", isLive: true },
  { title: "Vini Vintage Car", url: "https://vinivintagecar.online", category: "Travel", isLive: true },
  { title: "Escago Holidays", url: "https://escagoholidays.com", category: "Travel", isLive: true },
  { title: "Rev Mate", url: "https://rev-mate.in", category: "Travel", isLive: true },
  { title: "Unseen Ujjain", url: "https://unseenujjain.com", category: "Travel", isLive: true },
  { title: "Duniya Dekho Travels", url: "https://duniyadekhotravels.co.in/", category: "Travel", isLive: true },
  { title: "Srinivasan DNS Travels", url: "https://www.srinivasandnstravels.com/", category: "Travel", isLive: true },
  { title: "Premium Cab Goa", url: "https://www.premiumcabgoa.com/", category: "Travel", isLive: true },
  { title: "Goa Nitesh Tours And Travels", url: "https://goaniteshtoursandtravels.com", category: "Travel", isLive: true },
  { title: "The Jodhpur Taxi Services", url: "https://thejodhpurtaxiservices.com", category: "Travel", isLive: true },

  // Agency & International
  { title: "BB Signs New Zealand", url: "https://bbsigns.co.nz/", category: "International", isLive: true },
  { title: "Lax-Mi", url: "https://www.lax-mi.com", category: "Agency", isLive: true },
  
  // Sample Showcase
  { title: "Local Restaurant Website", url: "#", category: "Sample Showcase", isLive: false },
  { title: "Coaching Institute Website", url: "#", category: "Sample Showcase", isLive: false },
  { title: "Real Estate Landing Page", url: "#", category: "Sample Showcase", isLive: false }
];

export const categories = ["All", "Ecommerce", "Corporate", "Beauty & Fashion", "Food & Grocery", "Travel", "Healthcare", "Real Estate", "Photography", "Education", "Sample Showcase"];
